org: moullxndev
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  architecture: arm64
  memorySize: 128
  stage: ${opt:stage, "dev"}
  environment: ${file(./sls/config/env.yml)}

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool
    ClientName: ${self:service}-${self:provider.stage}-UserPoolClient

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
