Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.cognito.PoolName}
      DeletionProtection: ACTIVE
      MfaConfiguration: OFF
      AutoVerifiedAttributes:
        - email # cognito envia código de verificação pelo email automaticamente
      UsernameAttributes:
        - email # login é feito via email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false # se true, só admins podem criar usuários na pool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.cognito.ClientName}
      GenerateSecret: true # so quem tem a secret pode executar comandos na pool client. pro caso do client id vazar
      UserPoolId:
        Ref: UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
      TokenValidityUnits:
        AccessToken: hours
      AccessTokenValidity: 12
      RefreshTokenRotation:
        Feature: ENABLED
        RetryGracePeriodSeconds: 0
