updateProfile:
  handler: src/main/functions/profiles/update-profile.handler
  events:
    - httpApi:
        path: /profile
        method: PATCH
        authorizer:
          name: CognitoAuthorizer
