export enum ErrorCode {
  VALIDATION = "VALIDATION",
  // http
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  // application
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}
