statements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub "${MainTable.Arn}/index/*"

  - Effect: Allow
    Action: cognito-idp:AdminDeleteUser
    Resource:
      - !GetAtt UserPool.Arn

  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:DeleteObject
      - s3:GetObject
    Resource:
      - !Sub "${MealsBucket.Arn}/*"

  - Effect: Allow
    Action:
      - sqs:SendMessage
    Resource:
      - !GetAtt MealsQueue.Arn
